---
title: "Lichess Leaderboards"
author: "Gary Lu"
date: "2/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 12, fig.height = 6)
library(tidyverse)
library(rvest)
library(knitr)
```


```{r}
url <- "https://lichess.org/player"
page <- read_html(url)

# gametypehtml <- page %>% html_nodes("#powerTip , .user-top:nth-child(5) .text a , .user-top:nth-child(4) .text a , .user-top:nth-child(3) .text a , .user-top:nth-child(2) .text a , .user-top:nth-child(1) .text a")
# gametype <- html_text(gametypehtml)

# Regex to split name and rating
elosplit <- "(^.{1,})(\\d{4}$)"

#Scraping raw data

bulletplayershtml <- page %>% html_nodes(".user-top:nth-child(1) li")
bulletplayers <- html_text(bulletplayershtml)

blitzplayershtml <- page %>% html_nodes(".leaderboards .user-top:nth-child(2) li")
blitzplayers <- html_text(blitzplayershtml)

rapidplayershtml <- page %>% html_nodes(".user-top:nth-child(3) li")
rapidplayers <- html_text(rapidplayershtml)

classicalplayershtml <- page %>% html_nodes(".user-top:nth-child(4) li")
classicalplayers <- html_text(classicalplayershtml)

ultrabulletplayershtml <- page %>% html_nodes(".user-top:nth-child(5) li")
ultrabulletplayers <- html_text(ultrabulletplayershtml)

```

```{r}
# Cleaning Script

cleaning <- function(df, formatname){
  tibble(format = formatname, name = df) %>% extract(name, into = c("name", "rating"), regex = elosplit) %>% 
    mutate(rank = row_number())
}

bullet <- cleaning(bulletplayers, "Bullet")
blitz <- cleaning(blitzplayers, "Blitz")
classical <- cleaning(classicalplayers, "Classical")
ultrabullet <- cleaning(ultrabulletplayers, "UltraBullet")
table <- bind_rows(bullet, blitz, classical, ultrabullet) %>% group_by(format)
```

Finished table

```{r}
table
```

Visual Graphs

```{r}
plot <- ggplot(data = table, aes(x = rank, y = rating, group = format, color = format))+
  geom_label(aes(label = name, x = rank, y = rating))+
  labs(title = "Lichess Leaderboards",
       x = "")

plot+
  theme(axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.line.x.bottom = element_line(size = .5))
```


